# -*- coding: utf-8 -*-
"""Копия 2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckpt4Wdw_gzuF8bpy46rIZ-2QijoOxzY
"""

import numpy as np

print('Задание 1.')

# Найти с помощью NumPy SVD для матрицы:

A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

print(f'Матрица\n{A}')
print(f'SVD матрицы\n{np.linalg.svd(A)}')